### ISSUE TITLE
trouble running the example dataset

### ISSUE THREAD

**Issue by e-lerat** [GonzalezLab/T-lex2.5#5]
I have installed the program, I think properly. I have tried to run it on the dataset to make sure my install is correct. However, although the script indicates that it runs completely, there are many error messages due to some missing files, that should have been created during the run.

I have tried to nail the problem and it seems that bwa is never used (nor schrimp I think). I do not think it is normal. 

In particular, I do not understand, why, using the example datatest, the script never goes inside the "if" loop (below), and thus, never launches the generatefiles function, which prevents using bwa.

    while (defined( my $dir = readdir (DIR4))) {
      
	if ($dir !~ /\./) {
	    print "\nStrain: $dir\n";
	    my @files = <$inputdir/$dir/*>;
	    my $filelist = join (' ', @files);
	    if ($filelist =~ /\.fastq/) {
		print "$outputdir\/$dir\n"; 
		system ("mkdir $outputdir\/$dir") ; 
        	if ($binreads == 0) {
		    &generatefiles("$inputdir","$outputdir","$maxReadLength","$dir","$refgenome","$TE_map","$qual","$processes","$buffer","$junction");
       	 }
		&scorecounter("$dir","$outputdir\/$dir\/detection","$maxReadLength","$junction","$buffer","$lim","$id","$qual","$maxReadLength");
	    }	
	}
	else{
	    print "$dir\n";
	}
    }

here is the corresponding screen output

Strain data: /home/ubuntu/T-lex3-master/example/fastq_files/example
..
example_2.fastq
example_1.fastq
.

cat: 'tlex_example/Tpresence/*/detection/results': No such file or directory

If you have any idea, that would be great!

**Comment by e-lerat** [comment]
I figure out what the problem was.

**Comment by Nirmal2310** [comment]
Hey @e-lerat, I am facing the same issue while running T-Lex. Can you please tell me what the problem was and how you resolved it?

**Comment by e-lerat** [comment]
Hi @Nirmal2310 ,
I recall that it was a problem of path in the code toward the fastq data. I had to modify the code to indicate the right path.

**Comment by Nirmal2310** [comment]
Thank you so much @e-lerat
